cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from orders.views import order_create, OrderPayment, OrderDetailView, OrderAPIView, OrderPaymentAPIView

from rest_framework.routers import DefaultRouter

app_name = 'orders'

router = DefaultRouter()
router.register('payment', OrderAPIView, basename='payment')


urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('<int:pk>/qr/', OrderPayment.as_view(), name='order_qr'),
    path('<int:pk>/detail/', OrderDetailView.as_view(), name='order_detail'),

    path('<int:pk>/paid/<int:paid>/', OrderPaymentAPIView.as_view(), name='paid'),
]

urlpatterns += router.urls

ustora/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ustora_001.urls')),

    path('cart/', include('cart.urls', namespace='cart.cart')),

    path('order/', include('orders.urls', namespace='orders.orders')),
    path('captcha/', include('captcha.urls')),
    path('api/orders/', include('orders.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

ustora_001/urls.py
from django.urls import path
from ustora_001.views import ItemListView, ItemDetailView, items_bulk_edit, ItemCategoryView



app_name = 'ustora_001'



urlpatterns = [
    path('', ItemListView.as_view(), name="products_view"),
    path('<int:pk>/', ItemDetailView.as_view(), name="items_detail_view"),

    path('category/<int:pk>', ItemCategoryView.as_view(), name='items_category_view'),

    path('items_bulk_edit/', items_bulk_edit, name='items_bulk_edit'),





]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.CharField(label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    class Meta:
        fields = ('quantity', 'update')
        widgets = {
            'quantity': forms.TextInput(
                attrs={
                    'class': 'product_quantity_number js-number',
                    'value': 1,
                }),
            'update': forms.HiddenInput(),
        }

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ustora_001.models import Item
from .servises.cart import Cart
from .forms import CartAddProductForm

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], update_quantity=cd["update"])
    return redirect("cart:cart_detail")


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    return render(request, "cart_detail.html", {"cart": cart})

cart/templates/cart_detail.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    Продукт
{% endblock title %}


{% block nav %}
    <!-- Start Nav -->

    <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            <li><a href="#"><i class="fa fa-user"></i> My Account</a></li>
                            <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                            <li><a href="{% url 'cart:cart_detail' %}"><i class="fa fa-user"></i> My Cart</a></li>
                            <li><a href="checkout.html"><i class="fa fa-user"></i> Checkout</a></li>
                            <li><a href="#"><i class="fa fa-user"></i> Login</a></li>
                        </ul>
                    </div>
                </div>

                <!-- <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">currency :</span><span class="value">USD </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">USD</a></li>
                                    <li><a href="#">INR</a></li>
                                    <li><a href="#">GBP</a></li>
                                </ul>
                            </li>

                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">language :</span><span class="value">English </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">English</a></li>
                                    <li><a href="#">French</a></li>
                                    <li><a href="#">German</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div> -->
            </div>
        </div>
    </div>

    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="./"><img src="{% static 'img/logo.png' %}"></a></h1>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="shopping-item">

                        {% if cart.get_total_price == 0 %}
                            <a href="#">Cart - <span class="cart-amunt">$0</span> <i class="fa fa-shopping-cart"></i><span class="product-count">0</span></a>
                        {% else %}
                            {% for item in cart %}
                                <a href="#">Cart - <span class="cart-amunt">${{ item.total_price }}</span>
                                    <i class="fa fa-shopping-cart"></i>
                                        {% with product=item.product %}
                                            <span class="product-count">{{ item.quantity }}</span>
                                        {% endwith %}
                                </a>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- End Nav -->
    {% block panel %}
                <div class="mainmenu-area">
                    <div class="container">
                        <div class="row">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li><a href="{% url 'ustora_001:products_view' %}">Home</a></li>
                                    <li><a href="shop.html">Shop page</a></li>
                                    <li><a href="single-product.html">Single product</a></li>
                                    <li class="active"><a href="#">Cart</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="#">Category</a></li>
                                    <li><a href="#">Others</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock panel %}
{% endblock nav %}

{% block main %}

    <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Корзина</h2>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Page title area -->


    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="product-content-right">
                        <div class="woocommerce">

                            <section class="container">
                                {% if user.is_authenticated %}
                                <table class="cart table table-fluid">
                                    <thead>
                                        <tr>
                                            <th>Изображение</th>
                                            <th>Товар</th>
                                            <th>Количество</th>
                                            <th>Удалить</th>
                                            <th>Стоимость за единицу</th>
                                            <th>Цена</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in cart %}
                                            {% with product=item.product %}
                                                <tr>
                                                    <td>
                                                        <a href="{{ product.get_absolute_url }}">
                                                            <img src="
                                                                {% if product.images.all.0.image %}
                                                                    {{ product.images.all.0.image.url }}
                                                                {% else %}
                                                                    {{ product.image.url }}
                                                                {% endif %}" height="150">
                                                        </a>
                                                    </td>
                                                    <td>{{ product.name }}</td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td><a href="{% url 'cart:cart_remove' product.id%}">Удалить</a></td>
                                                    <td class="num">{{ item.new_price }}</td>
                                                    <td class="num">{{ item.total_price }}</td>
                                                </tr>
                                            {% endwith %}
                                        {% endfor %}
                                                <tr class="total">
                                                    <td>Итого</td>
                                                    <td colspan="4"></td>
                                                    <td class="num">{{ cart.get_total_price }}</td>
                                                </tr>
                                    </tbody>
                                </table>
                                <p class="text-right">
                                    <div class="btn-button-group mg-top-30 mg-bottom-15 bt-contact">
                                        <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="22" rel="nofollow" href="{% url 'orders:order_create' %}">Купить</a>
                                    </div>
                                </p>
                                {% else %}
                                    <p>Вы не авторизованы</p>
                                    <a href="{% url 'login' %}" class="button">Войти</a>
                                {% endif %}
                            </section>






                            <div class="cart-collaterals">


                            <div class="cross-sells">
                                <h2>You may be interested in...</h2>
                                <ul class="products">
                                    <li class="product">
                                        <a href="single-product.html">
                                            <img width="325" height="325" alt="T_4_front" class="attachment-shop_catalog wp-post-image" src="{% static 'img/product-2.jpg' %}">
                                            <h3>Ship Your Idea</h3>
                                            <span class="price"><span class="amount">£20.00</span></span>
                                        </a>

                                        <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="22" rel="nofollow" href="single-product.html">Select options</a>
                                    </li>

                                    <li class="product">
                                        <a href="single-product.html">
                                            <img width="325" height="325" alt="T_4_front" class="attachment-shop_catalog wp-post-image" src="{% static 'img/product-4.jpg' %}">
                                            <h3>Ship Your Idea</h3>
                                            <span class="price"><span class="amount">£20.00</span></span>
                                        </a>

                                        <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="22" rel="nofollow" href="single-product.html">Select options</a>
                                    </li>
                                </ul>
                            </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock main %}