cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

ustora/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ustora_001.urls')),

    path('cart/', include('cart.urls', namespace='cart.cart')),

    path('order/', include('orders.urls', namespace='orders.orders')),
    path('captcha/', include('captcha.urls')),
    path('api/orders/', include('orders.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

ustora_001/urls.py
from django.urls import path
from ustora_001.views import ItemListView, ItemDetailView, items_bulk_edit, ItemCategoryView



app_name = 'ustora_001'



urlpatterns = [
    path('', ItemListView.as_view(), name="products_view"),
    path('<int:pk>/', ItemDetailView.as_view(), name="items_detail_view"),

    path('category/<int:pk>', ItemCategoryView.as_view(), name='items_category_view'),

    path('items_bulk_edit/', items_bulk_edit, name='items_bulk_edit'),





]

ustora_001/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify

# Create your models here.

class Category(models.Model):
    name = models.CharField(
        verbose_name=_("Наименование"), max_length=200, db_index=True
    )
    slug = models.SlugField(verbose_name=_("slug"), max_length=200, unique=True)

    class Meta:
        verbose_name = _("Категория")
        verbose_name_plural = _("Категории")
        ordering = ("name",)

    def __str__(self) -> str:
        return f"{self.name}"


class Item(models.Model):
    name = models.CharField(verbose_name=_("Наименование"), max_length=200)
    description = models.TextField(verbose_name=_("Описание"), blank=True)
    new_price = models.DecimalField(verbose_name=_("Новая цена"), max_digits=10, decimal_places=2)
    old_price = models.DecimalField(verbose_name=_("Старая цена"), max_digits=10, decimal_places=2)
    slug = models.SlugField(verbose_name=_("slug"), max_length=200, unique=True)
    image = models.ImageField(
        verbose_name=_("Изображение"), upload_to="products", blank=True
    )
    images = models.ManyToManyField(
        to="ItemImage",
        verbose_name=_("Изображение"),
        blank=True,
        related_name="product_image",
    )
    stock = models.PositiveIntegerField(verbose_name=_("Наличие"), default=0)
    available = models.BooleanField(verbose_name=_("Доступен"), default=True)
    active = models.BooleanField(verbose_name=_("Активный"), default=True)
    in_stock = models.BooleanField(verbose_name=_("В продаже"), default=True)
    size = models.ForeignKey(
        to="ItemSize",
        verbose_name=_("Размер"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="product_size",
    )
    category = models.ForeignKey(
        to="Category",
        verbose_name=_("Категория"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="product_category",
    )
    sale = models.ForeignKey(
        to="ItemSale",
        verbose_name=_("Скидка"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="product_sale",
    )
    updated_at = models.DateTimeField(verbose_name=_("Обновлён"), auto_now=True)
    created_at = models.DateTimeField(verbose_name=_("Создан"), auto_now_add=True)
    order = models.SmallIntegerField(default=0, db_index=True)
    class Meta:
        ordering = ("order", "name",)
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        index_together = (("id", "slug"),)
        db_table = "ustora_001"

    def __str__(self) -> str:
        return f"{self.name}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Item, self).save(*args, **kwargs)


class ItemSet(models.Model):

    name = models.CharField(verbose_name=_("Наименование"), max_length=200)
    description = models.TextField(verbose_name=_("Описание"), blank=True)
    image = models.ImageField(
        verbose_name=_("Изображение"), upload_to="images/%Y/%m/%d", blank=True
    )

    set = models.ManyToManyField(
        to="Item",
        verbose_name=_("Наименование товаров"),
        related_name="item_set",
    )

    class Meta:
        verbose_name = _("Наименование списка товаров")
        verbose_name_plural = _("Наименования списка товаров")
        ordering = ("pk",)

        db_table = "ustora_001.ItemSet"

    def __str__(self) -> str:
        return f"{self.name}"


class ItemSale(models.Model):

    sale_begin = models.DateField(
        verbose_name=_("Начало скидки"), blank=True, null=True
    )
    sale_end = models.DateField(verbose_name=_("Конец скидки"), blank=True, null=True)
    sale_percent = models.DecimalField(
        verbose_name=_("Процент скидки"),
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True,
    )
    sale_discount = models.DecimalField(
        verbose_name=_("Скидка"), max_digits=10, decimal_places=2, blank=True, null=True
    )
    sale_price = models.DecimalField(
        verbose_name=_("Новая цена"), max_digits=10, decimal_places=2, blank=True, null=True
    )
    sale_total = models.DecimalField(
        verbose_name=_("Общая стоимость"),
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Скидка"
        verbose_name_plural = "Скидки"
        ordering = ("product_sale", "sale_begin", "sale_end")
        db_table = "ustora_001.ItemSale"

    def __str__(self) -> str:
        return f"Скидка продукта {self.product_sale.name}"


class ItemSize(models.Model):

    category = models.ForeignKey(
        to="Category",
        verbose_name=_("Категория"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="size_category",
    )
    size = models.CharField(verbose_name=_("Размер"), max_length=200)

    class Meta:
        verbose_name = "Размер"
        verbose_name_plural = "Размеры"
        ordering = ("category", "size")
        db_table = "ustora_001.ItemSize"

    def __str__(self) -> str:
        return f"Размер продукта {self.size} - {self.category}"


class ItemImage(models.Model):

    image = models.ImageField(
        verbose_name=_("Изображение"), upload_to="products/%Y/%m/%d", blank=True
    )
    alt = models.CharField(verbose_name=_("Подпись"), max_length=200, blank=True)
    description = models.TextField(verbose_name=_("Описание"), blank=True)

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"

    def __str__(self) -> str:
        return f"Ссылка на изображение продукта {self.image}"

ustora_001/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Item, ItemImage

class ItemForm(forms.ModelForm):
    error_css_class = 'error_class'
    class Meta:
        model = Item
        fields = '__all__'


    def clean(self):
        super().clean()
        errors = {}
        if self.cleaned_data.get('price') < 0:
            errors['price'] = ValidationError('Цена не может быть отрицательной')

        if errors:
            raise ValidationError(errors)

class ItemImageForm(forms.ModelForm):
    class Meta:
        model = ItemImage
        fields = '__all__'

ustora_001/views.py
from django.shortcuts import render, redirect, get_object_or_404

from cart.forms import CartAddProductForm
from ustora_001.models import Item, ItemSet, Category
from django.forms.formsets import ORDERING_FIELD_NAME
from django.forms import modelformset_factory
from django.views.generic import TemplateView, ListView, DetailView
from ustora_001.forms import ItemForm, ItemImageForm


# Create your views here.

# class ItemListView(TemplateView):
#     template_name = 'site.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['items'] = Item.objects.filter(in_stock=True)
#
#         return context

class ItemListView(TemplateView):
    template_name = 'site.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = Item.objects.prefetch_related('images').all()

        return context

class ItemDetailView(TemplateView):
    template_name = "products_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {"item": get_object_or_404(Item, in_stock=True, pk=self.kwargs["pk"])}

        return context

# class ItemDetailView(DetailView):
#     template_name = 'products_detail.html'
#     model = ItemSet
#     context_object_name = 'product_set'

class ItemCategoryView(DetailView):
    model = Category
    template_name = 'products_category.html'
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["items"] = Item.objects.filter(category=kwargs['object'])
        return context


# class ItemsListView(ListView):
#     model = ItemSet
#     template_name = 'products_list.html'
#     cart_product_form = CartAddProductForm()
#     context_object_name = 'products_set'

def item_detail(request, id, slug):
    product = get_object_or_404(Item, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    template_name = 'products_detail.html'
    context = {'product': product, 'cart_product_form': cart_product_form}

    return render(request, template_name=template_name, context=context)


def items_bulk_edit(request):
    ProductFormSet = modelformset_factory(
        Item, form=ItemImageForm, fields=('name', 'description', 'new_price', 'old_price', 'image'), extra=1, can_delete=True, can_order=True
    )
    template_name = 'product_bulk_edit.html'
    context = {}

    if request.method == 'POST':
        formset = ProductFormSet(request.POST)

        if formset.is_valid():
            for form in formset:
                if form.cleaned_data:
                    product = form.save(commit=False)
                    product.order = form.cleaned_data[ORDERING_FIELD_NAME]
                    product.save()
            return redirect('products:products_bulk_edit')
    else:
        formset = ProductFormSet(queryset=Item.objects.all())
    context['product_form_set'] = formset
    return render(request, template_name, context)

ustora_001/templates/footer.html
{% load static %}

<!-- Start Footer -->

<div class="footer-top-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="footer-about-us">
                    <h2>u<span>Stora</span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                    <div class="footer-social">
                        <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </div>
            
            <div class="col-md-3 col-sm-6">
                <div class="footer-menu">
                    <h2 class="footer-wid-title">User Navigation </h2>
                    <ul>
                        <li><a href="#">My account</a></li>
                        <li><a href="#">Order history</a></li>
                        <li><a href="#">Wishlist</a></li>
                        <li><a href="#">Vendor contact</a></li>
                        <li><a href="#">Front page</a></li>
                    </ul>                        
                </div>
            </div>
            
            <div class="col-md-3 col-sm-6">
                <div class="footer-menu">
                    <h2 class="footer-wid-title">Categories</h2>
                    <ul>
                        <li><a href="#">Mobile Phone</a></li>
                        <li><a href="#">Home accesseries</a></li>
                        <li><a href="#">LED TV</a></li>
                        <li><a href="#">Computer</a></li>
                        <li><a href="#">Gadets</a></li>
                    </ul>                        
                </div>
            </div>
            
            <div class="col-md-3 col-sm-6">
                <div class="footer-newsletter">
                    <h2 class="footer-wid-title">Newsletter</h2>
                    <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                    <div class="newsletter-form">
                        <form action="#">
                            <input type="email" placeholder="Type your email">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="footer-bottom-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="copyright">
                    <p>&copy; 2015 uCommerce. All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="footer-card-icon">
                    <i class="fa fa-cc-discover"></i>
                    <i class="fa fa-cc-mastercard"></i>
                    <i class="fa fa-cc-paypal"></i>
                    <i class="fa fa-cc-visa"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- End Footer -->

ustora_001/templates/nav.html
{% load static %}

<!-- Start Nav -->

<div class="header-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="user-menu">
                    <ul>
                        <li><a href="#"><i class="fa fa-user"></i> My Account</a></li>
                        <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                        <li><a href="{% url 'cart:cart_detail' %}"><i class="fa fa-user"></i> My Cart</a></li>
                        <li><a href="checkout.html"><i class="fa fa-user"></i> Checkout</a></li>
                        <li><a href="#"><i class="fa fa-user"></i> Login</a></li>
                    </ul>
                </div>
            </div>
            
            <!-- <div class="col-md-4">
                <div class="header-right">
                    <ul class="list-unstyled list-inline">
                        <li class="dropdown dropdown-small">
                            <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">currency :</span><span class="value">USD </span><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">USD</a></li>
                                <li><a href="#">INR</a></li>
                                <li><a href="#">GBP</a></li>
                            </ul>
                        </li>

                        <li class="dropdown dropdown-small">
                            <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">language :</span><span class="value">English </span><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">English</a></li>
                                <li><a href="#">French</a></li>
                                <li><a href="#">German</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div> -->
        </div>
    </div>
</div>

<div class="site-branding-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="logo">
                    <h1><a href="./"><img src="{% static 'img/logo.png' %}"></a></h1>
                </div>
            </div>
            
            <div class="col-sm-6">
                <div class="shopping-item">
                    <a href="cart.html">Cart - <span class="cart-amunt">$0</span> <i class="fa fa-shopping-cart"></i> <span class="product-count">0</span></a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="mainmenu-area">
    <div class="container">
        <div class="row">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        </div>
    </div>
</div>

<!-- End Nav -->

ustora_001/templates/product_bulk_edit.html
{% extends 'layout/base.html' %}
{% load static %}


        {% block title %}
            {{product_set.name }}
        {% endblock title %}


    {% block content %}

        {% block nav %}

        {% endblock nav %}

        {% block main %}
                <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url({{product_set.image.url}});">
                    <div class="overlay"></div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2 text-center">
                                <div class="display-t">
                                    <div class="display-tc animate-box" data-animate-effect="fadeIn">
                                        {% block header-text %}<h1>Items Bulk Edit</h1>{% endblock header-text %}
                                        <!-- <h2>Free html5 templates by <a href="https://themewagon.com/theme_tag/free/" target="_blank">Themewagon</a></h2> -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </header>

                <div id="fh5co-product">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1 animate-box">

                                <form action="{% url 'ustora_001:items_bulk_edit' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{ product_form_set.subject.errors }}
                                                {{ product_form_set.name.label_tag }}
                                                {{ product_form_set.as_p }}

                                                <input type="submit" value="Отправить" class="btn btn-primary btn-outline btn-lg">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
        {% endblock main %}

        {% block footer %}

        {% endblock footer %}

    {% endblock content %}

ustora_001/templates/products.html
{% load static %}

{% block products %}

        <div class="latest-product">
            <h2 class="section-title">Products</h2>

            <div class="product-carousel">

                {% for item_item in items %}
                    <div class="single-product">

                        <div class="product-f-image">
                            <img src="{{ item_item.image.url }}" alt="">
                            <div class="product-hover">
                                <a href="#" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                                <a href="{% url 'ustora_001:items_detail_view' item_item.pk %}" class="view-details-link"><i class="fa fa-link"></i> See details</a>
                            </div>
                        </div>

                        <h2><a href="{% url 'ustora_001:items_detail_view' item_item.pk %}">{{ item_item.name }}</a></h2>

                        <div class="product-carousel-price">
                            <ins>${{ item_item.new_price }}</ins> <del>${{ item_item.old_price }}</del>
                        </div>
                    </div>
                {% endfor %}

            </div>

        </div>

{% endblock products %}

ustora_001/templates/products_add.html
{% extends 'layout/base.html' %} 
{% block title %} Добавить студента {% endblock title %} 

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Добавить студента</h3>
        <div class="row">
          <div class="col-md-12">
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %} {{ form.as_p }}
              <button type="submit" class="btn btn-primary">
                Отправить
              </button>
              <a class="btn btn-info" href="{% url 'students_view' %}">Список студентов</a>
            </form>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

ustora_001/templates/products_category.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    {{ category.name }}
{% endblock title %}


{% block nav %}
    {% include 'nav.html' %}
    {% block panel %}
                <div class="mainmenu-area">
                    <div class="container">
                        <div class="row">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li><a href="{% url 'ustora_001:products_view' %}">Home</a></li>
                                    <li><a href="shop.html">Shop page</a></li>
                                    <li><a href="single-product.html">Single product</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li class="active"><a href="#">Category</a></li>
                                    <li><a href="#">Others</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock panel %}
{% endblock nav %}

{% block main %}

    <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Category products</h2>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Page title area -->


    <div class="single-product-area">

        <div class="zigzag-bottom"></div>

        <div class="container">

            <div class="row">


                {% for item in items  %}
                    <div class="col-md-3 col-sm-6">
                        <div class="single-shop-product">

                            <div class="product-upper">
                                {% if item.images.all.0.image.url %}
                                    <img src="{{ item.images.all.0.image.url }}" alt="">
                                {% else %}
                                    <img src="{{ item.image.url }}" alt="">
                                {% endif %}
                            </div>



                            <h2><a href="">{{ item.name }}</a></h2>

                            <div class="product-option-shop">
                                <h5>{{ item.description }}</h5>
                            </div>

                            <div class="product-carousel-price">
                                <ins>${{ item.new_price }}</ins> <del>${{ item.old_price }}</del>
                            </div>


                        </div>
                    </div>
                {% endfor %}




            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="product-pagination text-center">
                        <nav>
                          <ul class="pagination">
                            <li>
                              <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                              </a>
                            </li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li>
                              <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                              </a>
                            </li>
                          </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock main %}

ustora_001/templates/products_delete.html
{% extends 'layout/base.html' %}


{% block title %}
    Удалить {{ object }}
{% endblock title %}
    


{% block content %}
    <form method="post" action="{% url 'student_delete' object.pk %}">
        {% csrf_token %}
        <h3>Вы уверены, что хотите удалить студента {{ object }}?</h3>
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'students_view' %}" class="btn btn-primary">Отмена</a>
    </form>
    
{% endblock content %}
    

ustora_001/templates/site.html
{% extends 'layout/base.html' %}
{% load static %}


        {% block title %}
            Ustora Demo
        {% endblock title %}


    {% block content %}

        {% block nav %}
            {% include 'nav.html' %}
            {% block panel %}
                <div class="mainmenu-area">
                    <div class="container">
                        <div class="row">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="{% url 'ustora_001:products_view' %}">Home</a></li>
                                    <li><a href="#">Shop page</a></li>
                                    <li><a href="#">Single product</a></li>
                                    <li><a href="#">Cart</a></li>
                                    <li><a href="#">Checkout</a></li>
                                    <li><a href="#">Category</a></li>
                                    <li><a href="#">Others</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock panel %}
        {% endblock nav %}

        {% block main %}
            {% include 'main.html' %}
        {% endblock main %}

        {% block footer %}
            {% include 'footer.html' %}
        {% endblock footer %}

    {% endblock content %}